env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - plugin:react/recommended
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
  - '@typescript-eslint'
rules:
  {
    import/extensions: [error, ignorePackages, { js: never, jsx: never, ts: never, tsx: never }],
    no-shadow: 'off',
    no-unused-vars: 'off',
    no-param-reassign: 'off',
    react/jsx-filename-extension: 'off',
    react/jsx-uses-react: 'off',
    react/react-in-jsx-scope: 'off',
    react/require-default-props: 'off',
    quotes: ['error', 'single', { 'avoidEscape': true }],
    react/function-component-definition: ['error', { 'namedComponents': 'arrow-function' }]
  }
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
